# Generated by Django 6.0.3 on 2026-04-10 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('nid', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('front_part_image', models.ImageField(blank=True, null=True, upload_to='products/front/')),
                ('back_part_image', models.ImageField(blank=True, null=True, upload_to='products/back/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='products/documents/')),
                ('gg', models.TextField(blank=True, verbose_name='GG')),
                ('end_ply', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('yarn_composition', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('challenge_in', models.TextField(blank=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('knitting_smv', models.IntegerField(default=0)),
                ('linking_smv', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.buyer')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.staffprofile', verbose_name='Maker Name')),
            ],
        ),
    ]
