# Generated by Django 6.0.4 on 2026-05-16 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='back_part_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_part_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.staffprofile', verbose_name='Maker Name'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sample.product')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
