# Generated by Django 6.0.4 on 2026-05-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_remove_product_back_part_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_part_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/back/', verbose_name='Back Part Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='challenge_part_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/challenge/', verbose_name='Challenge Part Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_part_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/front/', verbose_name='Front Part Image'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
