# Generated by Django 6.0.4 on 2026-05-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_rename_product_to_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='style_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Style Number'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='back_part_image',
            field=models.ImageField(blank=True, null=True, upload_to='samples/back/', verbose_name='Back Part Image'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='challenge_part_image',
            field=models.ImageField(blank=True, null=True, upload_to='samples/challenge/', verbose_name='Challenge Part Image'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='samples/documents/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='front_part_image',
            field=models.ImageField(blank=True, null=True, upload_to='samples/front/', verbose_name='Front Part Image'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Sample Name'),
        ),
    ]
