# Generated by Django 6.0.4 on 2026-05-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_add_category_brand_gg_challengein'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.brand', verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='sample',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.category'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='challenge_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.challengein', verbose_name='Challenge In'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.gg', verbose_name='GG'),
        ),
    ]
