# Generated by Django 6.0.4 on 2026-05-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_link_sample_fk_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='Weight'),
        ),
    ]
