# Generated by Django 6.0.4 on 2026-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_weight_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='yarn_composition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yarn Composition'),
        ),
    ]
