# Generated by Django 6.0.4 on 2026-05-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_yarn_composition_to_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='challenge_part_image',
        ),
        migrations.CreateModel(
            name='ChallengeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='samples/challenge/')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_images', to='sample.sample')),
            ],
        ),
    ]
