# Generated by Django 6.0.4 on 2026-05-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_add_challenge_image_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='end_ply',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='knitting_smv',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='linking_smv',
        ),
    ]
