# Generated by Django 6.0.4 on 2026-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_remove_end_ply_knitting_linking_smv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='challenge_in',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='gg',
        ),
        migrations.AddField(
            model_name='sample',
            name='brand',
            field=models.ManyToManyField(blank=True, to='sample.brand', verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='sample',
            name='category',
            field=models.ManyToManyField(blank=True, to='sample.category'),
        ),
        migrations.AddField(
            model_name='sample',
            name='challenge_in',
            field=models.ManyToManyField(blank=True, to='sample.challengein', verbose_name='Challenge In'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gg',
            field=models.ManyToManyField(blank=True, to='sample.gg', verbose_name='GG'),
        ),
    ]
