# Generated by Django 6.0.4 on 2026-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_fk_to_m2m_category_brand_gg_challengein'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sample Type'),
        ),
        migrations.AddField(
            model_name='sample',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Season'),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('draft', 'Draft')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
