# Generated by Django 6.0.4 on 2026-05-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_add_sample_type_color_season_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='product_name',
        ),
    ]
