# Generated by Django 6.0.4 on 2026-06-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_remove_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
