# Generated by Django 6.0.4 on 2026-06-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_add_brand_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='maker',
        ),
        migrations.AddField(
            model_name='sample',
            name='maker',
            field=models.ManyToManyField(blank=True, to='sample.staffprofile', verbose_name='Maker Name'),
        ),
    ]
