# Generated by Django 6.0.4 on 2026-06-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0017_maker_fk_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='brand',
            field=models.ManyToManyField(blank=True, to='sample.brand', verbose_name='Brands'),
        ),
    ]
