# Generated by Django 6.0.4 on 2026-06-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0019_add_user_to_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='user',
        ),
    ]
