# Generated by Django 6.0.4 on 2026-06-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0020_remove_user_from_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Size'),
        ),
    ]
