# Generated by Django 6.0.4 on 2026-06-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0021_add_size_to_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Brand Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='origin',
            field=models.CharField(blank=True, choices=[('Afghanistan', '🇦🇫  Afghanistan'), ('Albania', '🇦🇱  Albania'), ('Algeria', '🇩🇿  Algeria'), ('Argentina', '🇦🇷  Argentina'), ('Australia', '🇦🇺  Australia'), ('Austria', '🇦🇹  Austria'), ('Azerbaijan', '🇦🇿  Azerbaijan'), ('Bangladesh', '🇧🇩  Bangladesh'), ('Belgium', '🇧🇪  Belgium'), ('Bolivia', '🇧🇴  Bolivia'), ('Brazil', '🇧🇷  Brazil'), ('Bulgaria', '🇧🇬  Bulgaria'), ('Cambodia', '🇰🇭  Cambodia'), ('Canada', '🇨🇦  Canada'), ('Chile', '🇨🇱  Chile'), ('China', '🇨🇳  China'), ('Colombia', '🇨🇴  Colombia'), ('Croatia', '🇭🇷  Croatia'), ('Czech Republic', '🇨🇿  Czech Republic'), ('Denmark', '🇩🇰  Denmark'), ('Ecuador', '🇪🇨  Ecuador'), ('Egypt', '🇪🇬  Egypt'), ('Ethiopia', '🇪🇹  Ethiopia'), ('Finland', '🇫🇮  Finland'), ('France', '🇫🇷  France'), ('Germany', '🇩🇪  Germany'), ('Ghana', '🇬🇭  Ghana'), ('Greece', '🇬🇷  Greece'), ('Guatemala', '🇬🇹  Guatemala'), ('Honduras', '🇭🇳  Honduras'), ('Hong Kong', '🇭🇰  Hong Kong'), ('Hungary', '🇭🇺  Hungary'), ('India', '🇮🇳  India'), ('Indonesia', '🇮🇩  Indonesia'), ('Iran', '🇮🇷  Iran'), ('Iraq', '🇮🇶  Iraq'), ('Ireland', '🇮🇪  Ireland'), ('Israel', '🇮🇱  Israel'), ('Italy', '🇮🇹  Italy'), ('Japan', '🇯🇵  Japan'), ('Jordan', '🇯🇴  Jordan'), ('Kazakhstan', '🇰🇿  Kazakhstan'), ('Kenya', '🇰🇪  Kenya'), ('South Korea', '🇰🇷  South Korea'), ('Kuwait', '🇰🇼  Kuwait'), ('Laos', '🇱🇦  Laos'), ('Lebanon', '🇱🇧  Lebanon'), ('Libya', '🇱🇾  Libya'), ('Malaysia', '🇲🇾  Malaysia'), ('Mexico', '🇲🇽  Mexico'), ('Morocco', '🇲🇦  Morocco'), ('Myanmar', '🇲🇲  Myanmar'), ('Nepal', '🇳🇵  Nepal'), ('Netherlands', '🇳🇱  Netherlands'), ('New Zealand', '🇳🇿  New Zealand'), ('Nigeria', '🇳🇬  Nigeria'), ('Norway', '🇳🇴  Norway'), ('Oman', '🇴🇲  Oman'), ('Pakistan', '🇵🇰  Pakistan'), ('Peru', '🇵🇪  Peru'), ('Philippines', '🇵🇭  Philippines'), ('Poland', '🇵🇱  Poland'), ('Portugal', '🇵🇹  Portugal'), ('Qatar', '🇶🇦  Qatar'), ('Romania', '🇷🇴  Romania'), ('Russia', '🇷🇺  Russia'), ('Saudi Arabia', '🇸🇦  Saudi Arabia'), ('Senegal', '🇸🇳  Senegal'), ('Singapore', '🇸🇬  Singapore'), ('South Africa', '🇿🇦  South Africa'), ('Spain', '🇪🇸  Spain'), ('Sri Lanka', '🇱🇰  Sri Lanka'), ('Sweden', '🇸🇪  Sweden'), ('Switzerland', '🇨🇭  Switzerland'), ('Taiwan', '🇹🇼  Taiwan'), ('Tanzania', '🇹🇿  Tanzania'), ('Thailand', '🇹🇭  Thailand'), ('Tunisia', '🇹🇳  Tunisia'), ('Turkey', '🇹🇷  Turkey'), ('Uganda', '🇺🇬  Uganda'), ('Ukraine', '🇺🇦  Ukraine'), ('United Arab Emirates', '🇦🇪  United Arab Emirates'), ('United Kingdom', '🇬🇧  United Kingdom'), ('United States', '🇺🇸  United States'), ('Uruguay', '🇺🇾  Uruguay'), ('Uzbekistan', '🇺🇿  Uzbekistan'), ('Venezuela', '🇻🇪  Venezuela'), ('Vietnam', '🇻🇳  Vietnam'), ('Yemen', '🇾🇪  Yemen'), ('Zimbabwe', '🇿🇼  Zimbabwe')], max_length=100, verbose_name='Origin Country'),
        ),
    ]
