# Generated by Django 6.0.4 on 2026-06-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0022_add_logo_to_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='maker_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Maker Name'),
        ),
    ]
