# Generated by Django 6.0.4 on 2026-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0023_add_maker_name_to_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
