# Generated by Django 6.0.4 on 2026-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0024_reduce_phone_number_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff/profiles/', verbose_name='Profile Picture'),
        ),
    ]
