# Generated by Django 6.0.4 on 2026-06-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0025_add_profile_picture_and_password_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='moisture_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Moisture Level'),
        ),
        migrations.AddField(
            model_name='sample',
            name='tech_pack',
            field=models.ImageField(blank=True, null=True, upload_to='samples/tech_pack/', verbose_name='Tech Pack'),
        ),
        migrations.AddField(
            model_name='sample',
            name='yarn_consumption',
            field=models.TextField(blank=True, verbose_name='Yarn Consumption'),
        ),
    ]
