# Generated by Django 6.0.4 on 2026-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0026_add_yarn_consumption_tech_pack_moisture_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='yarn_consumption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yarn Consumption'),
        ),
    ]
